name: Scheduled CI

on:
  schedule:
    # Every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Type Check
        run: npm run build --if-present

      - name: Run tests
        run: npm test --if-present

      - name: Package build artefacts
        if: success()
        run: |
          echo "Build succeeded at $(date)"

  # Optional: notify failures via GitHub issues or Slack webhook (placeholder)
